package org.vk.misproyectos.project_demovk;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Solicitud")
public class Solicitud implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("aprobacion_resolucion")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Boolean aprobacion_resolucion;
	@org.kie.api.definition.type.Label("aprobacion_informe")
	@org.kie.api.definition.type.Position(1)
	private java.lang.Boolean aprobacion_informe;

	@org.kie.api.definition.type.Label("expediente")
	@org.kie.api.definition.type.Position(2)
	private int expediente;

	@org.kie.api.definition.type.Label("encausado")
	@org.kie.api.definition.type.Position(3)
	private java.lang.String encausado;

	@org.kie.api.definition.type.Label("cargos_imputados")
	@org.kie.api.definition.type.Position(4)
	private java.lang.String cargos_imputados;

	@org.kie.api.definition.type.Label("asunto")
	@org.kie.api.definition.type.Position(5)
	private java.lang.String asunto;

	@org.kie.api.definition.type.Label("nombre_autoridad_judicial")
	@org.kie.api.definition.type.Position(6)
	private java.lang.String nombre_autoridad_judicial;

	@org.kie.api.definition.type.Label("cargo_autoridad_judicial")
	@org.kie.api.definition.type.Position(7)
	private java.lang.String cargo_autoridad_judicial;

	@org.kie.api.definition.type.Label("estado_extradicion")
	@org.kie.api.definition.type.Position(8)
	private java.lang.String estado_extradicion;

	@org.kie.api.definition.type.Label("observaciones")
	@org.kie.api.definition.type.Position(9)
	private java.lang.String observaciones;

	@org.kie.api.definition.type.Label("firma")
	@org.kie.api.definition.type.Position(10)
	private java.lang.Boolean firma;

	@org.kie.api.definition.type.Label(value = "aprobacion_informe_ext")
	@org.kie.api.definition.type.Position(value = 11)
	private java.lang.Boolean aprobacion_informe_ext;

	public java.lang.Boolean getAprobacion_resolucion() {
		return this.aprobacion_resolucion;
	}

	public void setAprobacion_resolucion(java.lang.Boolean aprobacion_resolucion) {
		this.aprobacion_resolucion = aprobacion_resolucion;
	}

	public java.lang.Boolean getAprobacion_informe() {
		return this.aprobacion_informe;
	}

	public void setAprobacion_informe(java.lang.Boolean aprobacion_informe) {
		this.aprobacion_informe = aprobacion_informe;
	}

	public int getExpediente() {
		return this.expediente;
	}

	public void setExpediente(int expediente) {
		this.expediente = expediente;
	}

	public java.lang.String getEncausado() {
		return this.encausado;
	}

	public void setEncausado(java.lang.String encausado) {
		this.encausado = encausado;
	}

	public java.lang.String getCargos_imputados() {
		return this.cargos_imputados;
	}

	public void setCargos_imputados(java.lang.String cargos_imputados) {
		this.cargos_imputados = cargos_imputados;
	}

	public java.lang.String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(java.lang.String asunto) {
		this.asunto = asunto;
	}

	public java.lang.String getNombre_autoridad_judicial() {
		return this.nombre_autoridad_judicial;
	}

	public void setNombre_autoridad_judicial(
			java.lang.String nombre_autoridad_judicial) {
		this.nombre_autoridad_judicial = nombre_autoridad_judicial;
	}

	public java.lang.String getCargo_autoridad_judicial() {
		return this.cargo_autoridad_judicial;
	}

	public void setCargo_autoridad_judicial(
			java.lang.String cargo_autoridad_judicial) {
		this.cargo_autoridad_judicial = cargo_autoridad_judicial;
	}

	public java.lang.String getEstado_extradicion() {
		return this.estado_extradicion;
	}

	public void setEstado_extradicion(java.lang.String estado_extradicion) {
		this.estado_extradicion = estado_extradicion;
	}

	public java.lang.String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(java.lang.String observaciones) {
		this.observaciones = observaciones;
	}

	public java.lang.Boolean getFirma() {
		return this.firma;
	}

	public void setFirma(java.lang.Boolean firma) {
		this.firma = firma;
	}

	public java.lang.Boolean getAprobacion_informe_ext() {
		return this.aprobacion_informe_ext;
	}

	public void setAprobacion_informe_ext(
			java.lang.Boolean aprobacion_informe_ext) {
		this.aprobacion_informe_ext = aprobacion_informe_ext;
	}

	public Solicitud() {
	}

	public Solicitud(java.lang.Boolean aprobacion_resolucion,
			java.lang.Boolean aprobacion_informe, int expediente,
			java.lang.String encausado, java.lang.String cargos_imputados,
			java.lang.String asunto,
			java.lang.String nombre_autoridad_judicial,
			java.lang.String cargo_autoridad_judicial,
			java.lang.String estado_extradicion,
			java.lang.String observaciones, java.lang.Boolean firma,
			java.lang.Boolean aprobacion_informe_ext) {
		this.aprobacion_resolucion = aprobacion_resolucion;
		this.aprobacion_informe = aprobacion_informe;
		this.expediente = expediente;
		this.encausado = encausado;
		this.cargos_imputados = cargos_imputados;
		this.asunto = asunto;
		this.nombre_autoridad_judicial = nombre_autoridad_judicial;
		this.cargo_autoridad_judicial = cargo_autoridad_judicial;
		this.estado_extradicion = estado_extradicion;
		this.observaciones = observaciones;
		this.firma = firma;
		this.aprobacion_informe_ext = aprobacion_informe_ext;
	}

}